version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      APP_INFRA: ${APP_INFRA:-origin}
      DB_HOST: clean-architecture-sample_db_1
    restart: always
    volumes:
      - ./:/go/src/github.com/ras0q/clean-architecture-sample
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: clean-architecture-sample
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
