// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package infrastructure

import (
	"github.com/Ras96/clean-architecture-sample/1_usecase/service"
	"github.com/Ras96/clean-architecture-sample/2_interface/handler"
	"github.com/Ras96/clean-architecture-sample/2_interface/repository"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InjectAPIServer() (handler.API, error) {
	sqlHandler := NewSQLHandler()
	userRepository := repository.NewUserRepository(sqlHandler)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	api := handler.NewAPI(userHandler)
	return api, nil
}

// wire.go:

// エンドポイントを増やした時はここに追加する
var (
	apiSet  = wire.NewSet(handler.NewAPI)
	sqlSet  = wire.NewSet(NewSQLHandler)
	userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, handler.NewUserHandler)
)
